---
title: "Chemical reaction networks"
---

Law of mass action = The rate at which a reaction occurs is directly proportional to the concentration of the reactant species.

Despite this simple formulation, mass-action systems are known which exhibit varied and exotic behaviour,
including stability, multistability, switching behaviour, finite escape time, oscillations, limit cycles,
chaotic behaviour, and Hopf bifurcations.

Mass-action kinteics = rate at which a reaction occurs is directly proportional to the concentation of the reactant species

Newtork that contains several reactions, then terms of this tyoe can b added together to obtain a mass model for the whole network.


Behaviours of mass-action systems also vary wildly
- a single steady state fot all choices of rate constants
- systems that have multiple steady states
- systems that oscillate
- systems that admit chaotic behaviours

To illustrate mass-action kinetics, consider the reaction network which gives rise to the following system of differential equations on the positive orthant.

GIVE EXAMPLE

EXPLAIN TRAJECTORY, CONCENTRATION AND STATE

Before we get started we need to introduce more definitions and notations.
Write the dynamical system in vector-based form:

1. Complex vectors
Objects which are source or the target of a reaction
It helps us workout the reaction rate function
GIVE EXAMPLE

2. Reaction vectors
The difference between the complex vectors of the target and the source of each reaction.
It records the stoichiometry of the reaction

A chemical reaction network can be regarded as a Euclidean embedded graph G = (V,E) as there is a defined oriented graph underlying a reaction network.
Graph where the vertices are complexes and the edges are reactions.
V = set of the vertices of the graph and E is the set of oriented edges.

Given a reaction network with its Euclidean embedded graph G, and given a vector of reaction rate constant k and using x^y ,
we can write the mass-action system generated by (G, k):

3. Stoichiometric subspace
S of a reaction network G is the vector space spanned by its reaction vectors

S = span {y' -y: y -> y'}

